In [ ]:
#0. Importando librería numpy 
import numpy as np

In [62]:
#1. Creamos la matriz con valores del 1 al 10
matrix_1 = np.arange(1,11,1)
matrix_1





array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
#2. Imprimimos la matriz 
print(matrix_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [64]:
#3. Imprimimos Máximo  y mínimo
print(max(matrix_1))
print(min(matrix_1))

10
1


In [ ]:
#4. Creamos array de 5 ceros 
matrix_2 = np.zeros( (5) )

#Imprimimos
print (Matrix_2)

[0. 0. 0. 0. 0.]


In [ ]:
#5. Creamos array de 5 unos
matrix_3 =np.ones(5)

#Imprimimos
print (Matrix_3)

[1. 1. 1. 1. 1.]


In [ ]:
#6.Crear la matriz
matrix_4 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


#7.Imprimimos
print (matrix_4)


[[1 2 3]
 [4 5 6]]


In [70]:
#8. Se utiliza .shapepara mostrar sus dimensiones.
matrix_4.shape

(2, 3)